
'use strict';

const HotKey = {
  key : [
  	 {value : '⌫' , keyCode: KeyEvent.DOM_VK_BACK_SPACE},
  	 {value : 'Tab' , keyCode: KeyEvent.DOM_VK_TAB},
  	 {value : 'Enter' , keyCode: KeyEvent.DOM_VK_RETURN},
  	 {value : 'Shift' , keyCode: KeyEvent.DOM_VK_SHIFT},
	 {value : 'Ctrl' , keyCode: KeyEvent.DOM_VK_CONTROL},
  	 {value : 'Alt' , keyCode: KeyEvent.DOM_VK_ALT},
	 {value : 'Pause/break' , keyCode: KeyEvent.DOM_VK_PAUSE},
  	 {value : 'Caps lock' , keyCode: KeyEvent.DOM_VK_CAPS_LOCK},
	 {value : 'Escape' , keyCode: KeyEvent.DOM_VK_ESCAPE},
   	 {value : 'Space' , keyCode: KeyEvent.DOM_VK_SPACE},

	 {value : 'Page up' , keyCode: KeyEvent.DOM_VK_PAGE_UP},
  	 {value : 'Page down' , keyCode: KeyEvent.DOM_VK_PAGE_DOWN},
	 {value : 'End' , keyCode: KeyEvent.DOM_VK_END},
 	 {value : 'Home' , keyCode: KeyEvent.DOM_VK_HOME},
	 {value : 'Left arrow' , keyCode: KeyEvent.DOM_VK_LEFT},
  	 {value : 'Up arrow' , keyCode: KeyEvent.DOM_VK_UP},
	 {value : 'Right arrow' , keyCode: KeyEvent.DOM_VK_RIGHT},
 	 {value : 'Down arrow' , keyCode: KeyEvent.DOM_VK_DOWN},
	 {value : 'Print Screen' , keyCode: KeyEvent.DOM_VK_PRINTSCREEN},
  	 {value : 'Insert' , keyCode: KeyEvent.DOM_VK_INSERT},
	 {value : 'Delete' , keyCode: KeyEvent.DOM_VK_DELETE},

  	 {value : 'Select key' , keyCode: KeyEvent.DOM_VK_CONTEXT_MENU},
  	 {value : 'Numpad 0' , keyCode: KeyEvent.DOM_VK_NUMPAD0},
  	 {value : 'Numpad 1' , keyCode: KeyEvent.DOM_VK_NUMPAD1},
	 {value : 'Numpad 2' , keyCode: KeyEvent.DOM_VK_NUMPAD2},
  	 {value : 'Numpad 3' , keyCode: KeyEvent.DOM_VK_NUMPAD3},
	 {value : 'Numpad 4' , keyCode: KeyEvent.DOM_VK_NUMPAD4},
  	 {value : 'Numpad 5' , keyCode: KeyEvent.DOM_VK_NUMPAD5},
	 {value : 'Numpad 6' , keyCode: KeyEvent.DOM_VK_NUMPAD6},
   	 {value : 'Numpad 7' , keyCode: KeyEvent.DOM_VK_NUMPAD7},
	 {value : 'Numpad 8' , keyCode: KeyEvent.DOM_VK_NUMPAD8},
  	 {value : 'Numpad 9' , keyCode: KeyEvent.DOM_VK_NUMPAD9},
	 {value : 'Multiply' , keyCode: KeyEvent.DOM_VK_MULTIPLY},
 	 {value : 'Add' , keyCode: KeyEvent.DOM_VK_AD},

	 {value : 'Subtract' , keyCode: KeyEvent.DOM_VK_SUBTRACT},
  	 {value : 'Decimal point' , keyCode: KeyEvent.DOM_VK_DECIMAL},
	 {value : 'Divide' , keyCode: KeyEvent.DOM_VK_DIVIDE},
 	 {value : 'F1' , keyCode: KeyEvent.DOM_VK_F1},
	 {value : 'F2' , keyCode: KeyEvent.DOM_VK_F2},
  	 {value : 'F3' , keyCode: KeyEvent.DOM_VK_F3},
	 {value : 'F4' , keyCode: KeyEvent.DOM_VK_F4},
  	 {value : 'F5' , keyCode: KeyEvent.DOM_VK_F5},
	 {value : 'F6' , keyCode: KeyEvent.DOM_VK_F6},
	 {value : 'F7' , keyCode: KeyEvent.DOM_VK_F7},
  	 {value : 'F8' , keyCode: KeyEvent.DOM_VK_F8},
	 {value : 'F9' , keyCode: KeyEvent.DOM_VK_F9},
  	 {value : 'F10' , keyCode: KeyEvent.DOM_VK_F10},
	 {value : 'F11' , keyCode: KeyEvent.DOM_VK_F11},
	 {value : 'F12' , keyCode: KeyEvent.DOM_VK_F12},
  	 {value : 'Num lock' , keyCode: KeyEvent.DOM_VK_NUM_LOCK},
	 {value : 'Scroll lock' , keyCode: KeyEvent.DOM_VK_SCROLL_LOCK},

  	 {value : ';' , keyCode: KeyEvent.DOM_VK_SEMICOLON},
	 {value : '=' , keyCode: KeyEvent.DOM_VK_EQUALS},
	 {value : ',' , keyCode: KeyEvent.DOM_VK_COMMA},
	 {value : '.' , keyCode: KeyEvent.DOM_VK_PERIOD},
	 {value : '/' , keyCode: KeyEvent.DOM_VK_SLASH},
	 {value : '`' , keyCode: KeyEvent.DOM_VK_BACK_QUOTE},
	 {value : '[' , keyCode: KeyEvent.DOM_VK_OPEN_BRACKET},
	 {value : '//' , keyCode: KeyEvent.DOM_VK_BACK_SLASH},
	 {value : ']' , keyCode: KeyEvent.DOM_VK_CLOSE_BRACKET},
	 {value : "'" , keyCode: KeyEvent.DOM_VK_QUOTE}
  ]
};
